root_path: /data/users/amezini/
datasets: [sepsis]

template_type: all
template_support: 85-100

noise_levels: ['01']#, '02', '03', '04']
portion: 1

alpha_levels: [0.15, 0.35, 0.55]

modes: [baseline, GLL, LLL]
nr_runs: 15
hidden_dim: 100
nr_epochs: 2000
min_epochs: 500
temperature: 0.7
batch_size: 64
patience: 35
min_delta: 0.00001
min_loss: 0.01
lr: 0.0005